### ISSUE TITLE
Literally

### ISSUE THREAD

**Issue by something-0001** [I-Skid/skid-stealer#1]
No wonder it's called "Skid Stealer", it's based off Moon Stealer lol.

**Comment by I-Skid** [comment]
dawg i made moon stealer lmao it got banned cus i dualhooked it, this one is dualhook free

**Comment by I-Skid** [comment]
also leave a star pls im tryna get famous like my old moon stealer this time i wanna play legit

**Comment by I-Skid** [comment]
how'd you know moon stealer, you my old friend or sum?

**Comment by TheCuteOwl** [comment]
> No wonder it's called "Skid Stealer", it's based off Moon Stealer lol.

Seriously, so like if i follow the logic

Moon stealer is W4sp Stealer and then Skid Stealer is Moon stealer which is W4sp
