### ISSUE TITLE
credit

### ISSUE THREAD

**Issue by burntchipset** [I-Skid/skid-stealer#5]
give credit to W4SP stealer

**Comment by burntchipset** [comment]
but still, nice stealer <3

**Comment by I-Skid** [comment]
i would give full credits 💀

**Comment by TheCuteOwl** [comment]
> but still, nice stealer <3

HOW THE, he just changed "w4sp" by "skid" like i dont see any change between them

**Comment by I-Skid** [comment]
i mean its called skid for a reason

**Comment by TheCuteOwl** [comment]
That's true xD
